#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged

npx concurrently \
  --kill-others-on-fail \
  --prefix "[{name}]" \
  --names "build" \
   --prefix-colors "bgRed.bold.white,bgGreen.bold.white" \
    "npm run build"
