export const movieListMock = [
  {
    id: 1,
    title: 'Secret Invasion',
    language: 'English',
    genre: 'Action',
    date: '2022',
    rating: 8,
    status: 'new',
  },
  {
    id: 2,
    title: 'Extraction 2',
    language: 'French',
    genre: 'Horror',
    date: '2021',
    rating: 7,
    status: 'featured',
  },
  {
    id: 3,
    title: 'Through My Window: Across the Sea',
    language: 'German',
    genre: 'Comedy',
    date: '2023',
    rating: 6,
    status: 'new',
  },
  {
    id: 4,
    title: 'The Flash',
    language: 'Spanish',
    genre: 'Drama',
    date: '2022',
    rating: 9,
    status: 'featured',
  },
  {
    id: 5,
    title: 'The Super Mario Bros. Movie',
    language: 'Italian',
    genre: 'Fantasy',
    date: '2023',
    rating: 7,
    status: 'new',
  },
  {
    id: 6,
    title: 'Spider-Man: Across the Spider-Verse',
    language: 'Russian',
    genre: 'Adventure',
    date: '2020',
    rating: 8,
    status: 'featured',
  },
  {
    id: 7,
    title: 'The Perfect Find',
    language: 'English',
    genre: 'Action',
    date: '2018',
    rating: 6,
    status: 'new',
  },
  {
    id: 8,
    title: 'John Wick: Chapter 4',
    language: 'French',
    genre: 'Horror',
    date: '2020',
    rating: 7,
    status: 'featured',
  },
  {
    id: 9,
    title: 'iNumber Number: Jozi Gold',
    language: 'German',
    genre: 'Comedy',
    date: '2012',
    rating: 6,
    status: 'new',
  },
  {
    id: 10,
    title: "Guy Ritchie's The Covenant",
    language: 'Spanish',
    genre: 'Drama',
    date: '2023',
    rating: 8,
    status: 'featured',
  },
  {
    id: 11,
    title: 'Avatar: The Way of Water',
    language: 'Italian',
    genre: 'Fantasy',
    date: '2010',
    rating: 7,
    status: 'new',
  },
  {
    id: 12,
    title: 'Make Me Believe',
    language: 'Russian',
    genre: 'Adventure',
    date: '2005',
    rating: 9,
    status: 'featured',
  },
  {
    id: 13,
    title: 'Black Mirror',
    language: 'English',
    genre: 'Comedy',
    date: '2011',
    rating: 6,
    status: 'new',
  },
  {
    id: 14,
    title: 'The Machine',
    language: 'French',
    genre: 'Action',
    date: '2010',
    rating: 7,
    status: 'featured',
  },
  {
    id: 15,
    title: 'Demon Slayer: Kimetsu no Yaiba',
    language: 'German',
    genre: 'Horror',
    date: '2021',
    rating: 5,
    status: 'new',
  },
  {
    id: 16,
    title: "I'm a Virgo",
    language: 'Spanish',
    genre: 'Drama',
    date: '2022',
    rating: 3,
    status: 'featured',
  },
  {
    id: 17,
    title: 'Black Adam',
    language: 'Italian',
    genre: 'Comedy',
    date: '2007',
    rating: 4,
    status: 'new',
  },
  {
    id: 18,
    title: 'Silo',
    language: 'Russian',
    genre: 'Fantasy',
    date: '2013',
    rating: 4,
    status: 'featured',
  },
  {
    id: 19,
    title: "Mother's Day",
    language: 'English',
    genre: 'Adventure',
    date: '2015',
    rating: 3,
    status: 'new',
  },
  {
    id: 20,
    title: 'Blood & Gold',
    language: 'French',
    genre: 'Classics',
    date: '2022',
    rating: 5,
    status: 'featured',
  },
];
