#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx concurrently \
  --kill-others-on-fail \
  --prefix "[{name}]" \
  --names "lint,typecheck,build" \
   --prefix-colors "bgRed.bold.white,bgGreen.bold.white,bgBlue.bold.white,bgMagenta.bold.white" \
    "npm run lint" \
    "npm run typecheck" \